---

- hosts: all
  sudo: yes
  tasks:

    - name: Update APT cache
      apt: update_cache="yes"

    - name: Install kernel developer tools
      apt: state=present pkg={{ item }}
      with_items:
          - linux-headers-{{ ansible_kernel }}
          - build-essential

